version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - pizza-app
  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      - mqtt
    networks:
      - pizza-app
      - order-network
    ports:
      - "5000:5000"
  redis:
    image: redis
    container_name: redis
    networks:
      - order-network
    ports:
      - "6379:6379"
  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    container_name: customer-service
    depends_on:
      - mqtt
    networks:
      - pizza-app
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command: '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - pizza-app
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - pizza-app
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_DASHBOARDS_JSON_ENABLED=true
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    
volumes:
  prometheus_data:
networks:
  pizza-app:
  order-network:

    
